spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vibespace
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: http://localhost:9200
server:
  port: 8080
